name: Basic Docker Deploy
on: 
  push:
    branches:
      - master

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Display folders
        run: ls
      - name: Build and Push Docker
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: nazohasavage/my_new_repo
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}